Repository santisq/PSCompression, pull requests merged in 2024-06, with the labels that each got.

#25 Fix example commands
  docs/en-US/Compress-ZipArchive.md
Labels: documentation

#27 Updates build process
  .vscode/launch.json
  CHANGELOG.md
  PSCompression.build.ps1
  ScriptAnalyzerSettings.psd1
  build.ps1
  tools/InvokeBuild.ps1
  tools/PesterTest.ps1
  tools/ProjectBuilder/Documentation.cs
  tools/ProjectBuilder/Extensions.cs
  tools/ProjectBuilder/Module.cs
  tools/ProjectBuilder/Pester.cs
  tools/ProjectBuilder/Project.cs
  tools/ProjectBuilder/ProjectBuilder.csproj
  tools/ProjectBuilder/ProjectInfo.cs
  tools/ProjectBuilder/Types.cs
  tools/prompt.ps1
  tools/requiredModules.psd1
Labels: enhancement

#29 Updates to README and Documentation
  README.md
  docs/en-US/ConvertFrom-GzipString.md
  docs/en-US/Expand-ZipEntry.md
  docs/en-US/Get-ZipEntry.md
  docs/en-US/Get-ZipEntryContent.md
  docs/en-US/New-ZipEntry.md
  docs/en-US/PSCompression.md
  docs/en-US/Remove-ZipEntry.md
  docs/en-US/Rename-ZipEntry.md
  docs/en-US/Set-ZipEntryContent.md
Labels: documentation, enhancement
